### ISSUE TITLE
Hello, how do I access the code you mentioned in this post?

### ISSUE THREAD

**Issue by muthukv** [danrue/danrue.github.com#1]

**Comment by danrue** [comment]
In what post?

**Comment by muthukv** [comment]
Hi Dan,
The post which explains about Harmonically Migrating from ClearCase to Git
I couldn't find any source code to try that.

Regards,
Vidya Muthukattil
Senior Tools support engineer
Air Traffic Management *
Thales Australia
Thales Australia Centre, WTC Northbank Wharf, Concourse Level,
Siddeley Street, Melbourne, VIC 3005, Australia
Tel: +61 3 8630 4464
vidya.muthukattil@thalesgroup.com.au<mailto:vidya.muthukattil@thalesgroup.com.au> | www.thalesgroup.com.au<http://www.thalesgroup.com.au>

**Comment by danrue** [comment]
Unfortunately I don't have any source code that I can make available. Hope it helped you anyway, 
Dan

**Comment by muthukv** [comment]
It does. Thanks Dan.

Vidya Muthukattil
Senior Tools support engineer
Air Traffic Management *
Thales Australia
Thales Australia Centre, WTC Northbank Wharf, Concourse Level,
Siddeley Street, Melbourne, VIC 3005, Australia
Tel: +61 3 8630 4464
vidya.muthukattil@thalesgroup.com.au<mailto:vidya.muthukattil@thalesgroup.com.au> | www.thalesgroup.com.au<http://www.thalesgroup.com.au>
